// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	graphql "github.com/Khan/genqlient/graphql"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// MakeRequest provides a mock function with given fields: ctx, req, resp
func (_m *Client) MakeRequest(ctx context.Context, req *graphql.Request, resp *graphql.Response) error {
	ret := _m.Called(ctx, req, resp)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *graphql.Request, *graphql.Response) error); ok {
		r0 = rf(ctx, req, resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
