version: "2"
run:
  go: "1.24"
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - noctx
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: true
    lll:
      line-length: 185
      tab-width: 8
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
