// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("gitlab")
	ScopeName = "github.com/liatrio/liatrio-otel-collector/receiver/gitlabreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
