// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("pipeline")
	ScopeName = "github.com/liatrio/liatrio-otel-collector/receiver/gitlabprocessor"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
