// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package githubscraper

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// BranchNode includes the requested fields of the GraphQL type Ref.
// The GraphQL type's documentation follows.
//
// Represents a Git reference.
type BranchNode struct {
	// The ref name.
	Name string `json:"name"`
	// Compares the current ref as a base ref to another head ref, if the comparison can be made.
	Compare BranchNodeCompareComparison `json:"compare"`
}

// GetName returns BranchNode.Name, and is useful for accessing the field via an interface.
func (v *BranchNode) GetName() string { return v.Name }

// GetCompare returns BranchNode.Compare, and is useful for accessing the field via an interface.
func (v *BranchNode) GetCompare() BranchNodeCompareComparison { return v.Compare }

// BranchNodeCompareComparison includes the requested fields of the GraphQL type Comparison.
// The GraphQL type's documentation follows.
//
// Represents a comparison between two commit revisions.
type BranchNodeCompareComparison struct {
	// The number of commits ahead of the base branch.
	AheadBy int `json:"aheadBy"`
	// The number of commits behind the base branch.
	BehindBy int `json:"behindBy"`
}

// GetAheadBy returns BranchNodeCompareComparison.AheadBy, and is useful for accessing the field via an interface.
func (v *BranchNodeCompareComparison) GetAheadBy() int { return v.AheadBy }

// GetBehindBy returns BranchNodeCompareComparison.BehindBy, and is useful for accessing the field via an interface.
func (v *BranchNodeCompareComparison) GetBehindBy() int { return v.BehindBy }

// CommitNode includes the requested fields of the GraphQL type Ref.
// The GraphQL type's documentation follows.
//
// Represents a Git reference.
type CommitNode struct {
	// The object the ref points to. Returns null when object does not exist.
	Target CommitNodeTargetGitObject `json:"-"`
}

// GetTarget returns CommitNode.Target, and is useful for accessing the field via an interface.
func (v *CommitNode) GetTarget() CommitNodeTargetGitObject { return v.Target }

func (v *CommitNode) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*CommitNode
		Target json.RawMessage `json:"target"`
		graphql.NoUnmarshalJSON
	}
	firstPass.CommitNode = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Target
		src := firstPass.Target
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalCommitNodeTargetGitObject(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal CommitNode.Target: %w", err)
			}
		}
	}
	return nil
}

type __premarshalCommitNode struct {
	Target json.RawMessage `json:"target"`
}

func (v *CommitNode) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *CommitNode) __premarshalJSON() (*__premarshalCommitNode, error) {
	var retval __premarshalCommitNode

	{

		dst := &retval.Target
		src := v.Target
		var err error
		*dst, err = __marshalCommitNodeTargetGitObject(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal CommitNode.Target: %w", err)
		}
	}
	return &retval, nil
}

// CommitNodeTargetBlob includes the requested fields of the GraphQL type Blob.
// The GraphQL type's documentation follows.
//
// Represents a Git blob.
type CommitNodeTargetBlob struct {
	Typename string `json:"__typename"`
}

// GetTypename returns CommitNodeTargetBlob.Typename, and is useful for accessing the field via an interface.
func (v *CommitNodeTargetBlob) GetTypename() string { return v.Typename }

// CommitNodeTargetCommit includes the requested fields of the GraphQL type Commit.
// The GraphQL type's documentation follows.
//
// Represents a Git commit.
type CommitNodeTargetCommit struct {
	Typename string `json:"__typename"`
	Id       string `json:"id"`
	// The linear commit history starting from (and including) this commit, in the same order as `git log`.
	History CommitNodeTargetCommitHistoryCommitHistoryConnection `json:"history"`
}

// GetTypename returns CommitNodeTargetCommit.Typename, and is useful for accessing the field via an interface.
func (v *CommitNodeTargetCommit) GetTypename() string { return v.Typename }

// GetId returns CommitNodeTargetCommit.Id, and is useful for accessing the field via an interface.
func (v *CommitNodeTargetCommit) GetId() string { return v.Id }

// GetHistory returns CommitNodeTargetCommit.History, and is useful for accessing the field via an interface.
func (v *CommitNodeTargetCommit) GetHistory() CommitNodeTargetCommitHistoryCommitHistoryConnection {
	return v.History
}

// CommitNodeTargetCommitHistoryCommitHistoryConnection includes the requested fields of the GraphQL type CommitHistoryConnection.
// The GraphQL type's documentation follows.
//
// The connection type for Commit.
type CommitNodeTargetCommitHistoryCommitHistoryConnection struct {
	// A list of edges.
	Edges []CommitNodeTargetCommitHistoryCommitHistoryConnectionEdgesCommitEdge `json:"edges"`
	// Information to aid in pagination.
	PageInfo CommitNodeTargetCommitHistoryCommitHistoryConnectionPageInfo `json:"pageInfo"`
}

// GetEdges returns CommitNodeTargetCommitHistoryCommitHistoryConnection.Edges, and is useful for accessing the field via an interface.
func (v *CommitNodeTargetCommitHistoryCommitHistoryConnection) GetEdges() []CommitNodeTargetCommitHistoryCommitHistoryConnectionEdgesCommitEdge {
	return v.Edges
}

// GetPageInfo returns CommitNodeTargetCommitHistoryCommitHistoryConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *CommitNodeTargetCommitHistoryCommitHistoryConnection) GetPageInfo() CommitNodeTargetCommitHistoryCommitHistoryConnectionPageInfo {
	return v.PageInfo
}

// CommitNodeTargetCommitHistoryCommitHistoryConnectionEdgesCommitEdge includes the requested fields of the GraphQL type CommitEdge.
// The GraphQL type's documentation follows.
//
// An edge in a connection.
type CommitNodeTargetCommitHistoryCommitHistoryConnectionEdgesCommitEdge struct {
	// The item at the end of the edge.
	Node CommitNodeTargetCommitHistoryCommitHistoryConnectionEdgesCommitEdgeNodeCommit `json:"node"`
}

// GetNode returns CommitNodeTargetCommitHistoryCommitHistoryConnectionEdgesCommitEdge.Node, and is useful for accessing the field via an interface.
func (v *CommitNodeTargetCommitHistoryCommitHistoryConnectionEdgesCommitEdge) GetNode() CommitNodeTargetCommitHistoryCommitHistoryConnectionEdgesCommitEdgeNodeCommit {
	return v.Node
}

// CommitNodeTargetCommitHistoryCommitHistoryConnectionEdgesCommitEdgeNodeCommit includes the requested fields of the GraphQL type Commit.
// The GraphQL type's documentation follows.
//
// Represents a Git commit.
type CommitNodeTargetCommitHistoryCommitHistoryConnectionEdgesCommitEdgeNodeCommit struct {
	// The datetime when this commit was committed.
	CommittedDate time.Time `json:"committedDate"`
}

// GetCommittedDate returns CommitNodeTargetCommitHistoryCommitHistoryConnectionEdgesCommitEdgeNodeCommit.CommittedDate, and is useful for accessing the field via an interface.
func (v *CommitNodeTargetCommitHistoryCommitHistoryConnectionEdgesCommitEdgeNodeCommit) GetCommittedDate() time.Time {
	return v.CommittedDate
}

// CommitNodeTargetCommitHistoryCommitHistoryConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// Information about pagination in a connection.
type CommitNodeTargetCommitHistoryCommitHistoryConnectionPageInfo struct {
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
}

// GetEndCursor returns CommitNodeTargetCommitHistoryCommitHistoryConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *CommitNodeTargetCommitHistoryCommitHistoryConnectionPageInfo) GetEndCursor() string {
	return v.EndCursor
}

// GetHasNextPage returns CommitNodeTargetCommitHistoryCommitHistoryConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *CommitNodeTargetCommitHistoryCommitHistoryConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// CommitNodeTargetGitObject includes the requested fields of the GraphQL interface GitObject.
//
// CommitNodeTargetGitObject is implemented by the following types:
// CommitNodeTargetBlob
// CommitNodeTargetCommit
// CommitNodeTargetTag
// CommitNodeTargetTree
// The GraphQL type's documentation follows.
//
// Represents a Git object.
type CommitNodeTargetGitObject interface {
	implementsGraphQLInterfaceCommitNodeTargetGitObject()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *CommitNodeTargetBlob) implementsGraphQLInterfaceCommitNodeTargetGitObject()   {}
func (v *CommitNodeTargetCommit) implementsGraphQLInterfaceCommitNodeTargetGitObject() {}
func (v *CommitNodeTargetTag) implementsGraphQLInterfaceCommitNodeTargetGitObject()    {}
func (v *CommitNodeTargetTree) implementsGraphQLInterfaceCommitNodeTargetGitObject()   {}

func __unmarshalCommitNodeTargetGitObject(b []byte, v *CommitNodeTargetGitObject) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Blob":
		*v = new(CommitNodeTargetBlob)
		return json.Unmarshal(b, *v)
	case "Commit":
		*v = new(CommitNodeTargetCommit)
		return json.Unmarshal(b, *v)
	case "Tag":
		*v = new(CommitNodeTargetTag)
		return json.Unmarshal(b, *v)
	case "Tree":
		*v = new(CommitNodeTargetTree)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing GitObject.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for CommitNodeTargetGitObject: "%v"`, tn.TypeName)
	}
}

func __marshalCommitNodeTargetGitObject(v *CommitNodeTargetGitObject) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *CommitNodeTargetBlob:
		typename = "Blob"

		result := struct {
			TypeName string `json:"__typename"`
			*CommitNodeTargetBlob
		}{typename, v}
		return json.Marshal(result)
	case *CommitNodeTargetCommit:
		typename = "Commit"

		result := struct {
			TypeName string `json:"__typename"`
			*CommitNodeTargetCommit
		}{typename, v}
		return json.Marshal(result)
	case *CommitNodeTargetTag:
		typename = "Tag"

		result := struct {
			TypeName string `json:"__typename"`
			*CommitNodeTargetTag
		}{typename, v}
		return json.Marshal(result)
	case *CommitNodeTargetTree:
		typename = "Tree"

		result := struct {
			TypeName string `json:"__typename"`
			*CommitNodeTargetTree
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for CommitNodeTargetGitObject: "%T"`, v)
	}
}

// CommitNodeTargetTag includes the requested fields of the GraphQL type Tag.
// The GraphQL type's documentation follows.
//
// Represents a Git tag.
type CommitNodeTargetTag struct {
	Typename string `json:"__typename"`
}

// GetTypename returns CommitNodeTargetTag.Typename, and is useful for accessing the field via an interface.
func (v *CommitNodeTargetTag) GetTypename() string { return v.Typename }

// CommitNodeTargetTree includes the requested fields of the GraphQL type Tree.
// The GraphQL type's documentation follows.
//
// Represents a Git tree.
type CommitNodeTargetTree struct {
	Typename string `json:"__typename"`
}

// GetTypename returns CommitNodeTargetTree.Typename, and is useful for accessing the field via an interface.
func (v *CommitNodeTargetTree) GetTypename() string { return v.Typename }

// PullRequestNode includes the requested fields of the GraphQL type PullRequest.
// The GraphQL type's documentation follows.
//
// A repository pull request.
type PullRequestNode struct {
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
	// `true` if the pull request is closed
	Closed bool `json:"closed"`
	// Identifies the date and time when the object was closed.
	ClosedAt time.Time `json:"closedAt"`
	// Whether or not the pull request was merged.
	Merged bool `json:"merged"`
	// The date and time that the pull request was merged.
	MergedAt time.Time `json:"mergedAt"`
	// Identifies the name of the head Ref associated with the pull request, even if the ref has been deleted.
	HeadRefName string `json:"headRefName"`
	// A list of reviews associated with the pull request.
	Reviews PullRequestNodeReviewsPullRequestReviewConnection `json:"reviews"`
}

// GetCreatedAt returns PullRequestNode.CreatedAt, and is useful for accessing the field via an interface.
func (v *PullRequestNode) GetCreatedAt() time.Time { return v.CreatedAt }

// GetClosed returns PullRequestNode.Closed, and is useful for accessing the field via an interface.
func (v *PullRequestNode) GetClosed() bool { return v.Closed }

// GetClosedAt returns PullRequestNode.ClosedAt, and is useful for accessing the field via an interface.
func (v *PullRequestNode) GetClosedAt() time.Time { return v.ClosedAt }

// GetMerged returns PullRequestNode.Merged, and is useful for accessing the field via an interface.
func (v *PullRequestNode) GetMerged() bool { return v.Merged }

// GetMergedAt returns PullRequestNode.MergedAt, and is useful for accessing the field via an interface.
func (v *PullRequestNode) GetMergedAt() time.Time { return v.MergedAt }

// GetHeadRefName returns PullRequestNode.HeadRefName, and is useful for accessing the field via an interface.
func (v *PullRequestNode) GetHeadRefName() string { return v.HeadRefName }

// GetReviews returns PullRequestNode.Reviews, and is useful for accessing the field via an interface.
func (v *PullRequestNode) GetReviews() PullRequestNodeReviewsPullRequestReviewConnection {
	return v.Reviews
}

// PullRequestNodeReviewsPullRequestReviewConnection includes the requested fields of the GraphQL type PullRequestReviewConnection.
// The GraphQL type's documentation follows.
//
// The connection type for PullRequestReview.
type PullRequestNodeReviewsPullRequestReviewConnection struct {
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
	// A list of nodes.
	Nodes []PullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview `json:"nodes"`
}

// GetTotalCount returns PullRequestNodeReviewsPullRequestReviewConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *PullRequestNodeReviewsPullRequestReviewConnection) GetTotalCount() int { return v.TotalCount }

// GetNodes returns PullRequestNodeReviewsPullRequestReviewConnection.Nodes, and is useful for accessing the field via an interface.
func (v *PullRequestNodeReviewsPullRequestReviewConnection) GetNodes() []PullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview {
	return v.Nodes
}

// PullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview includes the requested fields of the GraphQL type PullRequestReview.
// The GraphQL type's documentation follows.
//
// A review object for a given pull request.
type PullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview struct {
	// Identifies when the Pull Request Review was submitted
	SubmittedAt time.Time `json:"submittedAt"`
}

// GetSubmittedAt returns PullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview.SubmittedAt, and is useful for accessing the field via an interface.
func (v *PullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview) GetSubmittedAt() time.Time {
	return v.SubmittedAt
}

// SearchNode includes the requested fields of the GraphQL interface SearchResultItem.
//
// SearchNode is implemented by the following types:
// SearchNodeApp
// SearchNodeDiscussion
// SearchNodeIssue
// SearchNodeMarketplaceListing
// SearchNodeOrganization
// SearchNodePullRequest
// SearchNodeRepository
// SearchNodeUser
// The GraphQL type's documentation follows.
//
// The results of a search.
type SearchNode interface {
	implementsGraphQLInterfaceSearchNode()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *SearchNodeApp) implementsGraphQLInterfaceSearchNode()                {}
func (v *SearchNodeDiscussion) implementsGraphQLInterfaceSearchNode()         {}
func (v *SearchNodeIssue) implementsGraphQLInterfaceSearchNode()              {}
func (v *SearchNodeMarketplaceListing) implementsGraphQLInterfaceSearchNode() {}
func (v *SearchNodeOrganization) implementsGraphQLInterfaceSearchNode()       {}
func (v *SearchNodePullRequest) implementsGraphQLInterfaceSearchNode()        {}
func (v *SearchNodeRepository) implementsGraphQLInterfaceSearchNode()         {}
func (v *SearchNodeUser) implementsGraphQLInterfaceSearchNode()               {}

func __unmarshalSearchNode(b []byte, v *SearchNode) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "App":
		*v = new(SearchNodeApp)
		return json.Unmarshal(b, *v)
	case "Discussion":
		*v = new(SearchNodeDiscussion)
		return json.Unmarshal(b, *v)
	case "Issue":
		*v = new(SearchNodeIssue)
		return json.Unmarshal(b, *v)
	case "MarketplaceListing":
		*v = new(SearchNodeMarketplaceListing)
		return json.Unmarshal(b, *v)
	case "Organization":
		*v = new(SearchNodeOrganization)
		return json.Unmarshal(b, *v)
	case "PullRequest":
		*v = new(SearchNodePullRequest)
		return json.Unmarshal(b, *v)
	case "Repository":
		*v = new(SearchNodeRepository)
		return json.Unmarshal(b, *v)
	case "User":
		*v = new(SearchNodeUser)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing SearchResultItem.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for SearchNode: "%v"`, tn.TypeName)
	}
}

func __marshalSearchNode(v *SearchNode) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *SearchNodeApp:
		typename = "App"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchNodeApp
		}{typename, v}
		return json.Marshal(result)
	case *SearchNodeDiscussion:
		typename = "Discussion"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchNodeDiscussion
		}{typename, v}
		return json.Marshal(result)
	case *SearchNodeIssue:
		typename = "Issue"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchNodeIssue
		}{typename, v}
		return json.Marshal(result)
	case *SearchNodeMarketplaceListing:
		typename = "MarketplaceListing"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchNodeMarketplaceListing
		}{typename, v}
		return json.Marshal(result)
	case *SearchNodeOrganization:
		typename = "Organization"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchNodeOrganization
		}{typename, v}
		return json.Marshal(result)
	case *SearchNodePullRequest:
		typename = "PullRequest"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchNodePullRequest
		}{typename, v}
		return json.Marshal(result)
	case *SearchNodeRepository:
		typename = "Repository"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchNodeRepository
		}{typename, v}
		return json.Marshal(result)
	case *SearchNodeUser:
		typename = "User"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchNodeUser
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for SearchNode: "%T"`, v)
	}
}

// SearchNodeApp includes the requested fields of the GraphQL type App.
// The GraphQL type's documentation follows.
//
// A GitHub App.
type SearchNodeApp struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodeApp.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeApp) GetTypename() string { return v.Typename }

// SearchNodeDefaultBranchRef includes the requested fields of the GraphQL type Ref.
// The GraphQL type's documentation follows.
//
// Represents a Git reference.
type SearchNodeDefaultBranchRef struct {
	// The ref name.
	Name string `json:"name"`
}

// GetName returns SearchNodeDefaultBranchRef.Name, and is useful for accessing the field via an interface.
func (v *SearchNodeDefaultBranchRef) GetName() string { return v.Name }

// SearchNodeDiscussion includes the requested fields of the GraphQL type Discussion.
// The GraphQL type's documentation follows.
//
// A discussion in a repository.
type SearchNodeDiscussion struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodeDiscussion.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeDiscussion) GetTypename() string { return v.Typename }

// SearchNodeIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An Issue is a place to discuss ideas, enhancements, tasks, and bugs for a project.
type SearchNodeIssue struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodeIssue.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeIssue) GetTypename() string { return v.Typename }

// SearchNodeMarketplaceListing includes the requested fields of the GraphQL type MarketplaceListing.
// The GraphQL type's documentation follows.
//
// A listing in the GitHub integration marketplace.
type SearchNodeMarketplaceListing struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodeMarketplaceListing.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeMarketplaceListing) GetTypename() string { return v.Typename }

// SearchNodeOrganization includes the requested fields of the GraphQL type Organization.
// The GraphQL type's documentation follows.
//
// An account on GitHub, with one or more owners, that has repositories, members and teams.
type SearchNodeOrganization struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodeOrganization.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeOrganization) GetTypename() string { return v.Typename }

// SearchNodePullRequest includes the requested fields of the GraphQL type PullRequest.
// The GraphQL type's documentation follows.
//
// A repository pull request.
type SearchNodePullRequest struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodePullRequest.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodePullRequest) GetTypename() string { return v.Typename }

// SearchNodeRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type SearchNodeRepository struct {
	Typename string `json:"__typename"`
	Id       string `json:"id"`
	// The name of the repository.
	Name string `json:"name"`
	// The Ref associated with the repository's default branch.
	DefaultBranchRef SearchNodeDefaultBranchRef `json:"defaultBranchRef"`
}

// GetTypename returns SearchNodeRepository.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeRepository) GetTypename() string { return v.Typename }

// GetId returns SearchNodeRepository.Id, and is useful for accessing the field via an interface.
func (v *SearchNodeRepository) GetId() string { return v.Id }

// GetName returns SearchNodeRepository.Name, and is useful for accessing the field via an interface.
func (v *SearchNodeRepository) GetName() string { return v.Name }

// GetDefaultBranchRef returns SearchNodeRepository.DefaultBranchRef, and is useful for accessing the field via an interface.
func (v *SearchNodeRepository) GetDefaultBranchRef() SearchNodeDefaultBranchRef {
	return v.DefaultBranchRef
}

// SearchNodeUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type SearchNodeUser struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodeUser.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeUser) GetTypename() string { return v.Typename }

// __checkLoginInput is used internally by genqlient
type __checkLoginInput struct {
	Login string `json:"login"`
}

// GetLogin returns __checkLoginInput.Login, and is useful for accessing the field via an interface.
func (v *__checkLoginInput) GetLogin() string { return v.Login }

// __getBranchCountInput is used internally by genqlient
type __getBranchCountInput struct {
	Name  string `json:"name"`
	Owner string `json:"owner"`
}

// GetName returns __getBranchCountInput.Name, and is useful for accessing the field via an interface.
func (v *__getBranchCountInput) GetName() string { return v.Name }

// GetOwner returns __getBranchCountInput.Owner, and is useful for accessing the field via an interface.
func (v *__getBranchCountInput) GetOwner() string { return v.Owner }

// __getBranchDataInput is used internally by genqlient
type __getBranchDataInput struct {
	Name         string  `json:"name"`
	Owner        string  `json:"owner"`
	BranchFirst  int     `json:"branchFirst"`
	TargetBranch string  `json:"targetBranch"`
	BranchCursor *string `json:"branchCursor"`
}

// GetName returns __getBranchDataInput.Name, and is useful for accessing the field via an interface.
func (v *__getBranchDataInput) GetName() string { return v.Name }

// GetOwner returns __getBranchDataInput.Owner, and is useful for accessing the field via an interface.
func (v *__getBranchDataInput) GetOwner() string { return v.Owner }

// GetBranchFirst returns __getBranchDataInput.BranchFirst, and is useful for accessing the field via an interface.
func (v *__getBranchDataInput) GetBranchFirst() int { return v.BranchFirst }

// GetTargetBranch returns __getBranchDataInput.TargetBranch, and is useful for accessing the field via an interface.
func (v *__getBranchDataInput) GetTargetBranch() string { return v.TargetBranch }

// GetBranchCursor returns __getBranchDataInput.BranchCursor, and is useful for accessing the field via an interface.
func (v *__getBranchDataInput) GetBranchCursor() *string { return v.BranchCursor }

// __getCommitDataInput is used internally by genqlient
type __getCommitDataInput struct {
	Name         string  `json:"name"`
	Owner        string  `json:"owner"`
	BranchFirst  int     `json:"branchFirst"`
	CommitFirst  int     `json:"commitFirst"`
	CommitCursor *string `json:"commitCursor"`
	BranchName   string  `json:"branchName"`
}

// GetName returns __getCommitDataInput.Name, and is useful for accessing the field via an interface.
func (v *__getCommitDataInput) GetName() string { return v.Name }

// GetOwner returns __getCommitDataInput.Owner, and is useful for accessing the field via an interface.
func (v *__getCommitDataInput) GetOwner() string { return v.Owner }

// GetBranchFirst returns __getCommitDataInput.BranchFirst, and is useful for accessing the field via an interface.
func (v *__getCommitDataInput) GetBranchFirst() int { return v.BranchFirst }

// GetCommitFirst returns __getCommitDataInput.CommitFirst, and is useful for accessing the field via an interface.
func (v *__getCommitDataInput) GetCommitFirst() int { return v.CommitFirst }

// GetCommitCursor returns __getCommitDataInput.CommitCursor, and is useful for accessing the field via an interface.
func (v *__getCommitDataInput) GetCommitCursor() *string { return v.CommitCursor }

// GetBranchName returns __getCommitDataInput.BranchName, and is useful for accessing the field via an interface.
func (v *__getCommitDataInput) GetBranchName() string { return v.BranchName }

// __getPullRequestCountInput is used internally by genqlient
type __getPullRequestCountInput struct {
	Name  string `json:"name"`
	Owner string `json:"owner"`
}

// GetName returns __getPullRequestCountInput.Name, and is useful for accessing the field via an interface.
func (v *__getPullRequestCountInput) GetName() string { return v.Name }

// GetOwner returns __getPullRequestCountInput.Owner, and is useful for accessing the field via an interface.
func (v *__getPullRequestCountInput) GetOwner() string { return v.Owner }

// __getPullRequestDataInput is used internally by genqlient
type __getPullRequestDataInput struct {
	Name        string  `json:"name"`
	Owner       string  `json:"owner"`
	ReviewCount int     `json:"reviewCount"`
	PrFirst     int     `json:"prFirst"`
	PrCursor    *string `json:"prCursor"`
}

// GetName returns __getPullRequestDataInput.Name, and is useful for accessing the field via an interface.
func (v *__getPullRequestDataInput) GetName() string { return v.Name }

// GetOwner returns __getPullRequestDataInput.Owner, and is useful for accessing the field via an interface.
func (v *__getPullRequestDataInput) GetOwner() string { return v.Owner }

// GetReviewCount returns __getPullRequestDataInput.ReviewCount, and is useful for accessing the field via an interface.
func (v *__getPullRequestDataInput) GetReviewCount() int { return v.ReviewCount }

// GetPrFirst returns __getPullRequestDataInput.PrFirst, and is useful for accessing the field via an interface.
func (v *__getPullRequestDataInput) GetPrFirst() int { return v.PrFirst }

// GetPrCursor returns __getPullRequestDataInput.PrCursor, and is useful for accessing the field via an interface.
func (v *__getPullRequestDataInput) GetPrCursor() *string { return v.PrCursor }

// __getRepoDataBySearchInput is used internally by genqlient
type __getRepoDataBySearchInput struct {
	SearchQuery string  `json:"searchQuery"`
	RepoCursor  *string `json:"repoCursor"`
}

// GetSearchQuery returns __getRepoDataBySearchInput.SearchQuery, and is useful for accessing the field via an interface.
func (v *__getRepoDataBySearchInput) GetSearchQuery() string { return v.SearchQuery }

// GetRepoCursor returns __getRepoDataBySearchInput.RepoCursor, and is useful for accessing the field via an interface.
func (v *__getRepoDataBySearchInput) GetRepoCursor() *string { return v.RepoCursor }

// checkLoginOrganization includes the requested fields of the GraphQL type Organization.
// The GraphQL type's documentation follows.
//
// An account on GitHub, with one or more owners, that has repositories, members and teams.
type checkLoginOrganization struct {
	// The organization's login name.
	Login string `json:"login"`
}

// GetLogin returns checkLoginOrganization.Login, and is useful for accessing the field via an interface.
func (v *checkLoginOrganization) GetLogin() string { return v.Login }

// checkLoginResponse is returned by checkLogin on success.
type checkLoginResponse struct {
	// Lookup a user by login.
	User checkLoginUser `json:"user"`
	// Lookup a organization by login.
	Organization checkLoginOrganization `json:"organization"`
}

// GetUser returns checkLoginResponse.User, and is useful for accessing the field via an interface.
func (v *checkLoginResponse) GetUser() checkLoginUser { return v.User }

// GetOrganization returns checkLoginResponse.Organization, and is useful for accessing the field via an interface.
func (v *checkLoginResponse) GetOrganization() checkLoginOrganization { return v.Organization }

// checkLoginUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type checkLoginUser struct {
	// The username used to login.
	Login string `json:"login"`
}

// GetLogin returns checkLoginUser.Login, and is useful for accessing the field via an interface.
func (v *checkLoginUser) GetLogin() string { return v.Login }

// getBranchCountRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getBranchCountRepository struct {
	// Fetch a list of refs from the repository
	Refs getBranchCountRepositoryRefsRefConnection `json:"refs"`
}

// GetRefs returns getBranchCountRepository.Refs, and is useful for accessing the field via an interface.
func (v *getBranchCountRepository) GetRefs() getBranchCountRepositoryRefsRefConnection { return v.Refs }

// getBranchCountRepositoryRefsRefConnection includes the requested fields of the GraphQL type RefConnection.
// The GraphQL type's documentation follows.
//
// The connection type for Ref.
type getBranchCountRepositoryRefsRefConnection struct {
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// GetTotalCount returns getBranchCountRepositoryRefsRefConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *getBranchCountRepositoryRefsRefConnection) GetTotalCount() int { return v.TotalCount }

// getBranchCountResponse is returned by getBranchCount on success.
type getBranchCountResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getBranchCountRepository `json:"repository"`
}

// GetRepository returns getBranchCountResponse.Repository, and is useful for accessing the field via an interface.
func (v *getBranchCountResponse) GetRepository() getBranchCountRepository { return v.Repository }

// getBranchDataRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getBranchDataRepository struct {
	// Fetch a list of refs from the repository
	Refs getBranchDataRepositoryRefsRefConnection `json:"refs"`
}

// GetRefs returns getBranchDataRepository.Refs, and is useful for accessing the field via an interface.
func (v *getBranchDataRepository) GetRefs() getBranchDataRepositoryRefsRefConnection { return v.Refs }

// getBranchDataRepositoryRefsRefConnection includes the requested fields of the GraphQL type RefConnection.
// The GraphQL type's documentation follows.
//
// The connection type for Ref.
type getBranchDataRepositoryRefsRefConnection struct {
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
	// A list of nodes.
	Nodes []BranchNode `json:"nodes"`
	// Information to aid in pagination.
	PageInfo getBranchDataRepositoryRefsRefConnectionPageInfo `json:"pageInfo"`
}

// GetTotalCount returns getBranchDataRepositoryRefsRefConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *getBranchDataRepositoryRefsRefConnection) GetTotalCount() int { return v.TotalCount }

// GetNodes returns getBranchDataRepositoryRefsRefConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getBranchDataRepositoryRefsRefConnection) GetNodes() []BranchNode { return v.Nodes }

// GetPageInfo returns getBranchDataRepositoryRefsRefConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *getBranchDataRepositoryRefsRefConnection) GetPageInfo() getBranchDataRepositoryRefsRefConnectionPageInfo {
	return v.PageInfo
}

// getBranchDataRepositoryRefsRefConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// Information about pagination in a connection.
type getBranchDataRepositoryRefsRefConnectionPageInfo struct {
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
	// When paginating backwards, the cursor to continue.
	StartCursor string `json:"startCursor"`
}

// GetEndCursor returns getBranchDataRepositoryRefsRefConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *getBranchDataRepositoryRefsRefConnectionPageInfo) GetEndCursor() string { return v.EndCursor }

// GetStartCursor returns getBranchDataRepositoryRefsRefConnectionPageInfo.StartCursor, and is useful for accessing the field via an interface.
func (v *getBranchDataRepositoryRefsRefConnectionPageInfo) GetStartCursor() string {
	return v.StartCursor
}

// getBranchDataResponse is returned by getBranchData on success.
type getBranchDataResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getBranchDataRepository `json:"repository"`
}

// GetRepository returns getBranchDataResponse.Repository, and is useful for accessing the field via an interface.
func (v *getBranchDataResponse) GetRepository() getBranchDataRepository { return v.Repository }

// getCommitDataRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getCommitDataRepository struct {
	// Fetch a list of refs from the repository
	Refs getCommitDataRepositoryRefsRefConnection `json:"refs"`
}

// GetRefs returns getCommitDataRepository.Refs, and is useful for accessing the field via an interface.
func (v *getCommitDataRepository) GetRefs() getCommitDataRepositoryRefsRefConnection { return v.Refs }

// getCommitDataRepositoryRefsRefConnection includes the requested fields of the GraphQL type RefConnection.
// The GraphQL type's documentation follows.
//
// The connection type for Ref.
type getCommitDataRepositoryRefsRefConnection struct {
	// A list of nodes.
	Nodes []CommitNode `json:"nodes"`
}

// GetNodes returns getCommitDataRepositoryRefsRefConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getCommitDataRepositoryRefsRefConnection) GetNodes() []CommitNode { return v.Nodes }

// getCommitDataResponse is returned by getCommitData on success.
type getCommitDataResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getCommitDataRepository `json:"repository"`
}

// GetRepository returns getCommitDataResponse.Repository, and is useful for accessing the field via an interface.
func (v *getCommitDataResponse) GetRepository() getCommitDataRepository { return v.Repository }

// getPullRequestCountRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getPullRequestCountRepository struct {
	// A list of pull requests that have been opened in the repository.
	PullRequests getPullRequestCountRepositoryPullRequestsPullRequestConnection `json:"pullRequests"`
}

// GetPullRequests returns getPullRequestCountRepository.PullRequests, and is useful for accessing the field via an interface.
func (v *getPullRequestCountRepository) GetPullRequests() getPullRequestCountRepositoryPullRequestsPullRequestConnection {
	return v.PullRequests
}

// getPullRequestCountRepositoryPullRequestsPullRequestConnection includes the requested fields of the GraphQL type PullRequestConnection.
// The GraphQL type's documentation follows.
//
// The connection type for PullRequest.
type getPullRequestCountRepositoryPullRequestsPullRequestConnection struct {
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// GetTotalCount returns getPullRequestCountRepositoryPullRequestsPullRequestConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *getPullRequestCountRepositoryPullRequestsPullRequestConnection) GetTotalCount() int {
	return v.TotalCount
}

// getPullRequestCountResponse is returned by getPullRequestCount on success.
type getPullRequestCountResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getPullRequestCountRepository `json:"repository"`
}

// GetRepository returns getPullRequestCountResponse.Repository, and is useful for accessing the field via an interface.
func (v *getPullRequestCountResponse) GetRepository() getPullRequestCountRepository {
	return v.Repository
}

// getPullRequestDataRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getPullRequestDataRepository struct {
	// A list of pull requests that have been opened in the repository.
	PullRequests getPullRequestDataRepositoryPullRequestsPullRequestConnection `json:"pullRequests"`
}

// GetPullRequests returns getPullRequestDataRepository.PullRequests, and is useful for accessing the field via an interface.
func (v *getPullRequestDataRepository) GetPullRequests() getPullRequestDataRepositoryPullRequestsPullRequestConnection {
	return v.PullRequests
}

// getPullRequestDataRepositoryPullRequestsPullRequestConnection includes the requested fields of the GraphQL type PullRequestConnection.
// The GraphQL type's documentation follows.
//
// The connection type for PullRequest.
type getPullRequestDataRepositoryPullRequestsPullRequestConnection struct {
	// A list of nodes.
	Nodes []PullRequestNode `json:"nodes"`
	// Information to aid in pagination.
	PageInfo getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo `json:"pageInfo"`
}

// GetNodes returns getPullRequestDataRepositoryPullRequestsPullRequestConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getPullRequestDataRepositoryPullRequestsPullRequestConnection) GetNodes() []PullRequestNode {
	return v.Nodes
}

// GetPageInfo returns getPullRequestDataRepositoryPullRequestsPullRequestConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *getPullRequestDataRepositoryPullRequestsPullRequestConnection) GetPageInfo() getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo {
	return v.PageInfo
}

// getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// Information about pagination in a connection.
type getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
}

// GetHasNextPage returns getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo) GetEndCursor() string {
	return v.EndCursor
}

// getPullRequestDataResponse is returned by getPullRequestData on success.
type getPullRequestDataResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getPullRequestDataRepository `json:"repository"`
}

// GetRepository returns getPullRequestDataResponse.Repository, and is useful for accessing the field via an interface.
func (v *getPullRequestDataResponse) GetRepository() getPullRequestDataRepository {
	return v.Repository
}

// getRepoDataBySearchResponse is returned by getRepoDataBySearch on success.
type getRepoDataBySearchResponse struct {
	// Perform a search across resources, returning a maximum of 1,000 results.
	Search getRepoDataBySearchSearchSearchResultItemConnection `json:"search"`
}

// GetSearch returns getRepoDataBySearchResponse.Search, and is useful for accessing the field via an interface.
func (v *getRepoDataBySearchResponse) GetSearch() getRepoDataBySearchSearchSearchResultItemConnection {
	return v.Search
}

// getRepoDataBySearchSearchSearchResultItemConnection includes the requested fields of the GraphQL type SearchResultItemConnection.
// The GraphQL type's documentation follows.
//
// A list of results that matched against a search query. Regardless of the number of matches, a maximum of 1,000 results will be available across all types, potentially split across many pages.
type getRepoDataBySearchSearchSearchResultItemConnection struct {
	// The total number of repositories that matched the search query. Regardless of the total number of matches, a maximum of 1,000 results will be available across all types.
	RepositoryCount int `json:"repositoryCount"`
	// A list of edges.
	Edges []getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge `json:"edges"`
	// Information to aid in pagination.
	PageInfo getRepoDataBySearchSearchSearchResultItemConnectionPageInfo `json:"pageInfo"`
}

// GetRepositoryCount returns getRepoDataBySearchSearchSearchResultItemConnection.RepositoryCount, and is useful for accessing the field via an interface.
func (v *getRepoDataBySearchSearchSearchResultItemConnection) GetRepositoryCount() int {
	return v.RepositoryCount
}

// GetEdges returns getRepoDataBySearchSearchSearchResultItemConnection.Edges, and is useful for accessing the field via an interface.
func (v *getRepoDataBySearchSearchSearchResultItemConnection) GetEdges() []getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge {
	return v.Edges
}

// GetPageInfo returns getRepoDataBySearchSearchSearchResultItemConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *getRepoDataBySearchSearchSearchResultItemConnection) GetPageInfo() getRepoDataBySearchSearchSearchResultItemConnectionPageInfo {
	return v.PageInfo
}

// getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge includes the requested fields of the GraphQL type SearchResultItemEdge.
// The GraphQL type's documentation follows.
//
// An edge in a connection.
type getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge struct {
	// The item at the end of the edge.
	Node SearchNode `json:"-"`
}

// GetNode returns getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge.Node, and is useful for accessing the field via an interface.
func (v *getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge) GetNode() SearchNode {
	return v.Node
}

func (v *getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge
		Node json.RawMessage `json:"node"`
		graphql.NoUnmarshalJSON
	}
	firstPass.getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Node
		src := firstPass.Node
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalSearchNode(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge.Node: %w", err)
			}
		}
	}
	return nil
}

type __premarshalgetRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge struct {
	Node json.RawMessage `json:"node"`
}

func (v *getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge) __premarshalJSON() (*__premarshalgetRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge, error) {
	var retval __premarshalgetRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge

	{

		dst := &retval.Node
		src := v.Node
		var err error
		*dst, err = __marshalSearchNode(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal getRepoDataBySearchSearchSearchResultItemConnectionEdgesSearchResultItemEdge.Node: %w", err)
		}
	}
	return &retval, nil
}

// getRepoDataBySearchSearchSearchResultItemConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// Information about pagination in a connection.
type getRepoDataBySearchSearchSearchResultItemConnectionPageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
}

// GetHasNextPage returns getRepoDataBySearchSearchSearchResultItemConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *getRepoDataBySearchSearchSearchResultItemConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns getRepoDataBySearchSearchSearchResultItemConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *getRepoDataBySearchSearchSearchResultItemConnectionPageInfo) GetEndCursor() string {
	return v.EndCursor
}

// The query or mutation executed by checkLogin.
const checkLogin_Operation = `
query checkLogin ($login: String!) {
	user(login: $login) {
		login
	}
	organization(login: $login) {
		login
	}
}
`

func checkLogin(
	ctx context.Context,
	client graphql.Client,
	login string,
) (*checkLoginResponse, error) {
	req := &graphql.Request{
		OpName: "checkLogin",
		Query:  checkLogin_Operation,
		Variables: &__checkLoginInput{
			Login: login,
		},
	}
	var err error

	var data checkLoginResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getBranchCount.
const getBranchCount_Operation = `
query getBranchCount ($name: String!, $owner: String!) {
	repository(name: $name, owner: $owner) {
		refs(refPrefix: "refs/heads/") {
			totalCount
		}
	}
}
`

func getBranchCount(
	ctx context.Context,
	client graphql.Client,
	name string,
	owner string,
) (*getBranchCountResponse, error) {
	req := &graphql.Request{
		OpName: "getBranchCount",
		Query:  getBranchCount_Operation,
		Variables: &__getBranchCountInput{
			Name:  name,
			Owner: owner,
		},
	}
	var err error

	var data getBranchCountResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getBranchData.
const getBranchData_Operation = `
query getBranchData ($name: String!, $owner: String!, $branchFirst: Int!, $targetBranch: String!, $branchCursor: String) {
	repository(name: $name, owner: $owner) {
		refs(refPrefix: "refs/heads/", first: $branchFirst, after: $branchCursor) {
			totalCount
			nodes {
				name
				compare(headRef: $targetBranch) {
					aheadBy
					behindBy
				}
			}
			pageInfo {
				endCursor
				startCursor
			}
		}
	}
}
`

func getBranchData(
	ctx context.Context,
	client graphql.Client,
	name string,
	owner string,
	branchFirst int,
	targetBranch string,
	branchCursor *string,
) (*getBranchDataResponse, error) {
	req := &graphql.Request{
		OpName: "getBranchData",
		Query:  getBranchData_Operation,
		Variables: &__getBranchDataInput{
			Name:         name,
			Owner:        owner,
			BranchFirst:  branchFirst,
			TargetBranch: targetBranch,
			BranchCursor: branchCursor,
		},
	}
	var err error

	var data getBranchDataResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getCommitData.
const getCommitData_Operation = `
query getCommitData ($name: String!, $owner: String!, $branchFirst: Int!, $commitFirst: Int!, $commitCursor: String, $branchName: String!) {
	repository(name: $name, owner: $owner) {
		refs(refPrefix: "refs/heads/", first: $branchFirst, query: $branchName) {
			nodes {
				target {
					__typename
					... on Commit {
						id
						history(first: $commitFirst, after: $commitCursor) {
							edges {
								node {
									committedDate
								}
							}
							pageInfo {
								endCursor
								hasNextPage
							}
						}
					}
				}
			}
		}
	}
}
`

func getCommitData(
	ctx context.Context,
	client graphql.Client,
	name string,
	owner string,
	branchFirst int,
	commitFirst int,
	commitCursor *string,
	branchName string,
) (*getCommitDataResponse, error) {
	req := &graphql.Request{
		OpName: "getCommitData",
		Query:  getCommitData_Operation,
		Variables: &__getCommitDataInput{
			Name:         name,
			Owner:        owner,
			BranchFirst:  branchFirst,
			CommitFirst:  commitFirst,
			CommitCursor: commitCursor,
			BranchName:   branchName,
		},
	}
	var err error

	var data getCommitDataResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getPullRequestCount.
const getPullRequestCount_Operation = `
query getPullRequestCount ($name: String!, $owner: String!) {
	repository(name: $name, owner: $owner) {
		pullRequests {
			totalCount
		}
	}
}
`

func getPullRequestCount(
	ctx context.Context,
	client graphql.Client,
	name string,
	owner string,
) (*getPullRequestCountResponse, error) {
	req := &graphql.Request{
		OpName: "getPullRequestCount",
		Query:  getPullRequestCount_Operation,
		Variables: &__getPullRequestCountInput{
			Name:  name,
			Owner: owner,
		},
	}
	var err error

	var data getPullRequestCountResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getPullRequestData.
const getPullRequestData_Operation = `
query getPullRequestData ($name: String!, $owner: String!, $reviewCount: Int!, $prFirst: Int!, $prCursor: String) {
	repository(name: $name, owner: $owner) {
		pullRequests(first: $prFirst, after: $prCursor) {
			nodes {
				... on PullRequest {
					createdAt
					closed
					closedAt
					merged
					mergedAt
				}
				headRefName
				reviews(states: APPROVED, last: $reviewCount) {
					totalCount
					nodes {
						... on PullRequestReview {
							submittedAt
						}
					}
				}
			}
			pageInfo {
				hasNextPage
				endCursor
			}
		}
	}
}
`

func getPullRequestData(
	ctx context.Context,
	client graphql.Client,
	name string,
	owner string,
	reviewCount int,
	prFirst int,
	prCursor *string,
) (*getPullRequestDataResponse, error) {
	req := &graphql.Request{
		OpName: "getPullRequestData",
		Query:  getPullRequestData_Operation,
		Variables: &__getPullRequestDataInput{
			Name:        name,
			Owner:       owner,
			ReviewCount: reviewCount,
			PrFirst:     prFirst,
			PrCursor:    prCursor,
		},
	}
	var err error

	var data getPullRequestDataResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getRepoDataBySearch.
const getRepoDataBySearch_Operation = `
query getRepoDataBySearch ($searchQuery: String!, $repoCursor: String) {
	search(query: $searchQuery, type: REPOSITORY, first: 100, after: $repoCursor) {
		repositoryCount
		edges {
			node {
				__typename
				... on Repository {
					id
					name
					defaultBranchRef {
						name
					}
				}
			}
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func getRepoDataBySearch(
	ctx context.Context,
	client graphql.Client,
	searchQuery string,
	repoCursor *string,
) (*getRepoDataBySearchResponse, error) {
	req := &graphql.Request{
		OpName: "getRepoDataBySearch",
		Query:  getRepoDataBySearch_Operation,
		Variables: &__getRepoDataBySearchInput{
			SearchQuery: searchQuery,
			RepoCursor:  repoCursor,
		},
	}
	var err error

	var data getRepoDataBySearchResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
