extensions:
  basicauth/github:
    client_auth:
      username: ${env:GH_USER}
      password: ${env:GH_PAT}

receivers:
  otlp:
    protocols:
      grpc:

  gitprovider:
    initial_delay: 1s
    collection_interval: 60s
    scrapers:
      github:
        github_org: adrielp
        auth:
          authenticator: basicauth/github

  ldap:
    interval: 10s
    search_filter: "(objectclass=*)"
    endpoint: "localhost"
    base_dn: "dc=example,dc=org"
    ignore_tls: true
  
processors:
  
exporters:
  logging:
    verbosity: detailed

  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

service:
  extensions: [basicauth/github]
  pipelines:
    metrics:
      receivers: [otlp, gitprovider]
      processors: []
      exporters: [logging]
  telemetry:
    logs:
      level: debug
