---
name: Lint PR

on:
    pull_request:
        types:
            - opened
            - edited
            - synchronize

jobs:
    main:
        name: Validate PR title (Convention Commit)
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: thehanimo/pr-title-checker@v1.3.4
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
