---
name: PR Linter

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Get Octo STS Token
        uses: octo-sts/action@bc99912863e5d0ca5cb08f77804c9922a088265f
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: pr-lint-format

      - name: Clone repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          fetch-depth: 0

      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
