---
name: Pull Request Labeler
on:
    - pull_request_target

jobs:
    labeler:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/labeler@v5
