---
name: Install Tools

on:
  pull_request:
    branches: [main]
    paths:
      - '**/Dockerfile'
      - '**/.dockerignore'
      - .github/**
      - '**.go'
      - '**.mod'
      - '**.sum'
      - config/**
      - '**/Makefile*'
      - '**/documentation.md'
      - .golangci.yaml
      - .goreleaser.yaml

  push:
    branches: [main]

jobs:
  install-tools:
    name: install-tools
    strategy:
      matrix:
        GOOS: [darwin, linux, windows]
        GOARCH: [arm64, amd64, '386']
        go: ['1.22']
        exclude:
          - GOOS: darwin
            GOARCH: '386'
          - GOOS: darwin
            GOARCH: arm
          - GOOS: windows
            GOARCH: arm
          - GOOS: windows
            GOARCH: arm64
    # runs-on: ubuntu-latest
    runs-on:
      group: bigger
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Set up Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: ${{ matrix.go }}
      #     cache: true
      #     cache-dependency-path: |
      #       go.sum
      #       receiver/**/go.sum
      #       extension/**/go.sum
      #       internal/**/tools/go.sum
      #       cmd/**/go.sum

      - name: Make install-tools
        run: make install-tools

      - name: Cache Tools
        id: cache-tools
        uses: actions/cache@v4
        with:
          path: |
            .tools/
          key: go-${{ matrix.go }}-arch-${{ matrix.GOARCH }}-os-${{ matrix.GOOS }}-tools
