// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("githubactions")
	ScopeName = "github.com/liatrio/liatrio-otel-collector/receiver/githubactionsreceiver"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
